name: Unlock ruby dependencies

needs:
  packages:
    - busybox

pipeline:
  - runs: |
      find . -name '*.gemspec' -exec sed -e 's/~>/>=/' -i {} \;
      find . -name 'Gemfile.lock' -exec sed -e 's/~>/>=/' -i {} \;
