name: Collect wheels built by a python pipeline

needs:
  packages:
    - util-linux

inputs:
  dest:
    description: the destination
    default: ${{targets.subpkgdir}}/usr/share/wheels

pipeline:
  - name: "pip build ${{inputs.python}}"
    runs: |
      found=""
      set --
      for wheel in ./.wheels/*/*.whl; do
          [ -f "$wheel" ] || continue
          set -- "$@" "$wheel"
      done
      if [ $# -eq 0 ]; then
          echo "No wheels found in $PWD/.wheels/*/*.whl"
          exit 1
      fi
      mkdir -p ${{inputs.dest}}
      echo "Found wheels:" "$@"
      sha256sum "$@"
      cp -v "$@" "${{inputs.dest}}"
