name: Runs ruff NPY201 checks

needs:
  packages:
    - ruff

inputs:
  path:
    description: the path to run the checks over
    default: .

pipeline:
  - name: "ruff check ${{inputs.path}}"
    runs: |
      ruff check $path --select NPY201
