package:
  name: gifticlib
  version: "1.17"
  epoch: 0
  description: IO library for the GIFTI cortical surface data format
  url: https://github.com/NIFTI-Imaging/gifti_clib
  copyright:
    # Public domain https://github.com/NIFTI-Imaging/nifti_clib/blob/master/LICENSE
    - license: custom

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - cmake
      - expat-dev
      - nifticlib-dev
      - samurai
      - zlib-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/NIFTI-Imaging/gifti_clib
      expected-commit: d3e873d8539d9b469daf7db04093da1d7e73d4f7

  - uses: cmake/configure
    with:
      opts: |
        -DUSE_SYSTEM_NIFTI=ON

  - uses: cmake/build

  - uses: cmake/install

  - uses: strip

subpackages:
  - name: gifticlib-dev
    description: gifticlib dev
    dependencies:
      runtime:
        - expat-dev
        - nifticlib-dev
        - zlib-dev
    pipeline:
      - uses: split/dev
    test:
      pipeline:
        - uses: test/tw/ldd-check

update:
  # Version tracks github commits
  enabled: false
  release-monitor:
    identifier: 386489

test:
  pipeline:
    - uses: test/tw/ldd-check
