package:
  name: qrupdate
  version: "1.1.5"
  description: Fork of the qrupdate library for future maintenance
  url: https://gitlab.mpi-magdeburg.mpg.de/koehlerm/qrupdate-ng
  target-architecture:
    - x86_64
    - aarch64
  copyright:
    - license: GPL-3.0-only

environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
      - ./melange.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
      - ./packages
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - cmake
      - coreutils
      - gfortran
      - ninja-build # samurai doesn't provide a new enough version
      - openblas-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://gitlab.mpi-magdeburg.mpg.de/koehlerm/qrupdate-ng.git
      tag: v${{package.version}}
      expected-commit: 279971db6b140b663c71b1e205d80e2795558388

  - runs: |
      sed -i 's/CMAKE_MINIMUM_REQUIRED(VERSION 3.1.0)/CMAKE_MINIMUM_REQUIRED(VERSION 3.5.0)/' ./CMakeLists.txt

  - uses: cmake/configure
    with:
      opts: |
        -DCMAKE_MAKE_PROGRAM="/usr/lib/ninja-build/bin/ninja"

  - uses: cmake/build

  - uses: cmake/install

  - uses: strip

subpackages:
  - name: qrupdate-dev
    description: qrupdate dev
    pipeline:
      - uses: split/dev

update:
  enabled: true
  release-monitor:
    identifier: 319990
