package:
  name: niimath
  version: "1.0.20250804"
  epoch: 0
  description: niimath - a clone of fslmaths
  url: https://github.com/rordenlab/niimath
  copyright:
    - license: BSD-2-Clause

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - zlib-dev

pipeline:
  - uses: git-checkout
    with:
      expected-commit: c4756e5186183b9c6005834562cec209f1184406
      repository: https://github.com/rordenlab/niimath
      tag: v${{package.version}}
  - runs: |
      cd src
      make all -j$(nproc)
      install -D niimath "${{targets.destdir}}/usr/bin/niimath"

update:
  enabled: true
  release-monitor:
    identifier: 386425

test:
  pipeline:
    - runs: |
        niimath
