package:
  name: tcsh
  version: "6.24.16"
  description: C shell with file name completion and command line editing
  url: https://www.tcsh.org
  target-architecture:
    - x86_64
    - aarch64
  copyright:
    - license: BSD-4-Clause-UC

environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - ncurses-dev

pipeline:
  - uses: fetch
    with:
      expected-sha256: 4208cf4630fb64d91d81987f854f9570a5a0e8a001a92827def37d0ed8f37364
      uri: https://astron.com/pub/tcsh/tcsh-${{package.version}}.tar.gz

  - uses: autoconf/configure
    with:
      opts: |
        --host=${{host.triplet.gnu}} \
        --build=${{host.triplet.gnu}} \
        --prefix=/usr \
        --sysconfdir=/etc \
        --mandir=/usr/share/man \
        --infodir=/usr/share/info

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

update:
  enabled: true
  release-monitor:
    identifier: 4945

test:
  environment:
    contents:
      packages:
        - wolfi-base
  pipeline:
    - runs: |
        tcsh --version
